INSERT INTO skills (title) VALUES
  ('Angular'),
  ('Apache HTTP Server'),
  ('Apache Kafka'),
  ('Apache Struts'),
  ('ASP.NET Core'),
  ('Beego'),
  ('Blazor'),
  ('Boost'),
  ('Buffalo'),
  ('C#'),
  ('C++'),
  ('Cassandra'),
  ('CSS'),
  ('Cuba'),
  ('Django'),
  ('Docker'),
  ('Echo'),
  ('Express.js'),
  ('FastAPI'),
  ('Firebase'),
  ('Figma'),
  ('Flask'),
  ('Gin'),
  ('Git'),
  ('Go'),
  ('Grails'),
  ('Hanami'),
  ('Hibernate'),
  ('HTML'),
  ('Java'),
  ('JavaScript'),
  ('jQuery'),
  ('Kitura'),
  ('Kotlin'),
  ('Ktor'),
  ('Kubernetes'),
  ('Laravel'),
  ('LESS'),
  ('Litestar'),
  ('Micronaut'),
  ('MongoDB'),
  ('MySQL'),
  ('NestJS'),
  ('nginx'),
  ('Node.js'),
  ('OpenCV'),
  ('Oracle Database'),
  ('Padrino'),
  ('Perfect'),
  ('PHP'),
  ('PostgreSQL'),
  ('Postman'),
  ('PyQt'),
  ('Pyramid'),
  ('Pytest'),
  ('Python'),
  ('PyTorch'),
  ('Qt'),
  ('RabbitMQ'),
  ('React.js'),
  ('Redis'),
  ('Revel'),
  ('Ruby'),
  ('Ruby on Rails'),
  ('RxSwift'),
  ('SASS'),
  ('SCSS'),
  ('Selenium'),
  ('Sinatra'),
  ('Spark Kotlin'),
  ('Spring'),
  ('SQLAlchemy'),
  ('SQLite'),
  ('Svelte'),
  ('Swift'),
  ('SwiftUI'),
  ('TensorFlow'),
  ('Tornado'),
  ('TypeScript'),
  ('Unity'),
  ('Unreal Engine'),
  ('Vapor'),
  ('Vert.x'),
  ('Vue.js'),
  ('WebSocket'),
  ('Windows Forms'),
  ('WPF'),
  ('Xamarin');