version: '3.8'

services:
  fastapi:
    build: .
    command: sh run.sh
    container_name: fastapi
    image: fastapi:0.1
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app:
    driver: bridge
